name: "Daily ARC-AGI Puzzle Post"

on:
  schedule:
    - cron: "5 8 * * *" # Every day at 08:05 UTC
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Test secret variable
      run: |
        echo "BSKY_HANDLE is set to: $BSKY_HANDLE"
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pipeline
      run: |
        python pipeline.py --github-token $GITHUB_TOKEN --bsky-handle $BSKY_HANDLE --bsky-pwd $BSKY_PASSWORD --puzzle_id today
        